### ISSUE TITLE
Unexpected behavior: AdvancementFactory#getAllItems also adds icon to list of item objects

### ISSUE THREAD

**Issue by ifvictr** [Trigary/AdvancementCreator#3]
Hi,

I attempted to create an advancement that is granted when the player collects all the music discs. Here’s the code:

```java
Advancement allMusicDiscs = factory.getAllItems("all_music_discs", root, "Musicophile",
        "Collect every single music disc", Material.JUKEBOX, Material.MUSIC_DISC_11,
        Material.MUSIC_DISC_13, Material.MUSIC_DISC_BLOCKS, Material.MUSIC_DISC_CAT,
        Material.MUSIC_DISC_CHIRP, Material.MUSIC_DISC_FAR, Material.MUSIC_DISC_MALL,
        Material.MUSIC_DISC_MELLOHI, Material.MUSIC_DISC_STAL, Material.MUSIC_DISC_STRAD,
        Material.MUSIC_DISC_WAIT, Material.MUSIC_DISC_WARD);
```

The expected behavior is for it to generate an advancement with a jukebox icon and the 12 discs as the requirement, but this happens instead:

<img width="501" alt="Screen Shot 2020-02-16 at 16 38 07" src="https://user-images.githubusercontent.com/10110245/74616100-bf40a980-50da-11ea-967a-caa57a4fd6ac.png">

The jukebox also becomes a requirement for the advancement.

**EDIT:** Looked through the code and also found this problem with getAllItemsOnce, getAnyItem, getItem, getPlaceAllItems, getPlaceAnyBlock, getPlaceAnyItem, and getPlaceItem.

**Comment by Trigary** [comment]
That is the intended behaviour I'm afraid. Use a non-auto-activating factory, remove the `Material.JUKEBOX` from the varargs parameter and manually set it as the icon of the advancement.

**Comment by ifvictr** [comment]
That would work if there was a setIcon method, but there isn't. I think it'd be much easier to just exclude the first ItemObject in the varargs parameter.

```java
// from this:
return getAll(id, parent, title, description, items[0].getItem(), items, item -> new InventoryChangedTrigger().addItem(item));
// to this:
return getAll(id, parent, title, description, items[0].getItem(), Arrays.copyOfRange(items, 1, items.length), item -> new InventoryChangedTrigger().addItem(item));
```

Or the parameter types could be changed (i.e. allowing a Material icon to be passed in with ItemObjects, and vice versa). I don't think library should assume that the icon is an item the user wants to include as a criteria, so this would be a welcome change.

**Comment by Trigary** [comment]
The factories can't please all use cases, we would end up with a million methods and there are already too many. You can manually set the icon of an advancement: `Advancement#getIcon` returns a mutable value, as per JavaDocs.

Maybe you are right and there should be a way to set the icon in the factory, but I currently have no intentions of making any changes like that - I haven't even checked whether any changes for 1.15.2 are necessary.
